# Generated by Django 4.0.1 on 2022-12-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_detail',
            name='email',
        ),
    ]
