# Generated by Django 3.1.7 on 2021-09-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_playable_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
