# Generated by Django 4.0.1 on 2022-12-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_about_detail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_detail',
            name='github',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about_detail',
            name='linkedin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about_detail',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about_detail',
            name='greeting',
            field=models.TextField(blank=True, null=True),
        ),
    ]
