# Generated by Django 3.1.7 on 2021-11-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_doctag_uploaddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_embed_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
